modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile="icon.png"
    credits="${mod_credits}"
    authors = "${mod_author}"
    description = '''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"