modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile="icon.png"
    credits="${mod_credits}"
    authors = "${mod_author}"
    description = '''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    versionRange = "${neoforge_loader_version_range}"
    ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
    side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
    modId = "minecraft"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"